### ISSUE TITLE
[Bug]: (1.18.2 Forge 40.1.51) Equipping Ice Skates Crashes Game

### ISSUE THREAD

**Issue by LivingLandmine** [Joo5h/Winter-Overhaul#9]
### Bug Description

When someone equips the ice skates in my modpack, the server crashes.  Glazing over the crash report, it seems to be talking about rendering them a lot.

I'm wondering if one or more of the mods I have in the pack are conflicting with Winter Overhaul?  The crash report is below.

[crash-2022-06-21_16.26.22-client.txt](https://github.com/Joo5h/Winter-Overhaul/files/8952662/crash-2022-06-21_16.26.22-client.txt)

### How to Reproduce?

1. With the mod installed, Launch Minecraft 1.18.2 with Forge version 40.1.51
2. Enter creative world and try to equip the ice skates
3. The game crashes

### Expected Behavior

The game doesn't crash when equipping the ice skates.

### Version

1.0.1

### Mod Loader Version

1.18.2 - 40.1.51

**Comment by ThatGravyBoat** [comment]
This is an optifine crash not winter overhaul

**Comment by Gatamigo** [comment]
Same issue, with only Winter Overhaul and geckolib installed. My crash reports pointed to multiple other mods in my pack until I finally realized it was the ice skates specifically that were causing the problem. 

[crash-2022-07-08_17.19.26-client.txt](https://github.com/Joo5h/Winter-Overhaul/files/9075105/crash-2022-07-08_17.19.26-client.txt)
